// src/pages/contact.jsx
import React from "react";
import { Layout, ContactForm } from "../components";
import { PageHeader, Container } from "../primitives";

const ContactPage = () => (
  <>
    <Layout pageTitle="Contact">
      <PageHeader
        title="Contact"
        subtitle="Want to get in touch with me? Sweet! Just fill out the form and I'll get right back to you."
      />
      <Container>
        <ContactForm centered />
      </Container>
    </Layout>
  </>
);

export default ContactPage;

// src/routes/contact.svelte
<script lang="ts">
  import PageHeader from "$lib/components/page-header.svelte";
  import ContactForm from "$lib/components/contact-form.svelte";
</script>

<main>
  <PageHeader
    title="Get in Touch"
    description="Want to get in touch with me? Sweet! Just fill out the form and I'll get back to you as soon as
    possible."
  />

  <div class="max-w-6xl mx-auto px-4 py-16 sm:py-24">
    <ContactForm />
  </div>
</main>
